# Generated by Django 4.0.5 on 2022-06-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendar',
            table='calendar',
        ),
        migrations.AlterModelTable(
            name='line',
            table='lines',
        ),
        migrations.AlterModelTable(
            name='route',
            table='routes',
        ),
        migrations.AlterModelTable(
            name='shape',
            table='shapes',
        ),
        migrations.AlterModelTable(
            name='stop',
            table='stops',
        ),
        migrations.AlterModelTable(
            name='stoptime',
            table='stop_times',
        ),
        migrations.AlterModelTable(
            name='trip',
            table='trips',
        ),
    ]
