# Generated by Django 4.0.5 on 2022-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0002_alter_calendar_table_alter_line_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='stop_num',
            new_name='stop_number',
        ),
        migrations.RemoveField(
            model_name='route',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_long_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_type',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='service_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_short_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shape',
            name='shape_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='stop_headsign',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='shape_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_headsign',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
