# Generated by Django 4.0.5 on 2022-06-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0003_rename_stop_num_stop_stop_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Line',
            new_name='RoutesPassed',
        ),
        migrations.RenameField(
            model_name='routespassed',
            old_name='line',
            new_name='routes_passed',
        ),
        migrations.AlterModelTable(
            name='routespassed',
            table='routes_passed',
        ),
    ]
