# Generated by Django 4.0.5 on 2022-07-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0004_rename_line_routespassed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoptime',
            name='drop_off_type',
        ),
        migrations.RemoveField(
            model_name='stoptime',
            name='pickup_type',
        ),
    ]
