# Generated by Django 4.0.5 on 2022-07-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbus', '0005_remove_stoptime_drop_off_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoutesPassed',
        ),
    ]
